const firebaseErrorMessages: { [key: string]: string } = {
    "auth/email-already-in-use": "Email already in use",
    "auth/invalid-email": "Invalid email address",
    "auth/invalid-password": "Invalid password",
    "auth/weak-password": "Weak password, should be at least 6 characters",
    "auth/claims-too-large": "The claims payload is too large",
    "auth/email-already-exists": "The provided email is already in use",
    "auth/id-token-expired": "The session has expired, please log in again",
    "auth/id-token-revoked":
        "The session has been revoked, please log in again",
    "auth/insufficient-permission":
        "Insufficient permission to perform this action",
    "auth/internal-error":
        "An unexpected error occurred, please try again later",
    "auth/invalid-login-credentials": "Invalid login of password",
    "auth/invalid-argument": "Invalid argument provided",
    "auth/invalid-claims": "Invalid claims provided",
    "auth/invalid-continue-uri": "Invalid continue URL",
    "auth/invalid-creation-time": "Invalid creation time",
    "auth/invalid-credential": "Invalid credential",
    "auth/invalid-disabled-field": "Invalid disabled field value",
    "auth/invalid-display-name": "Invalid display name",
    "auth/invalid-dynamic-link-domain": "Invalid dynamic link domain",
    "auth/invalid-email-verified": "Invalid email verification value",
    "auth/invalid-hash-algorithm": "Invalid hash algorithm",
    "auth/invalid-hash-block-size": "Invalid hash block size",
    "auth/invalid-hash-derived-key-length": "Invalid hash derived key length",
    "auth/invalid-hash-key": "Invalid hash key",
    "auth/invalid-hash-memory-cost": "Invalid hash memory cost",
    "auth/invalid-hash-parallelization": "Invalid hash parallelization",
    "auth/invalid-hash-rounds": "Invalid hash rounds",
    "auth/invalid-hash-salt-separator": "Invalid hash salt separator",
    "auth/invalid-id-token": "Invalid ID token",
    "auth/invalid-last-sign-in-time": "Invalid last sign-in time",
    "auth/invalid-page-token": "Invalid page token",
    "auth/invalid-password-hash": "Invalid password hash",
    "auth/invalid-password-salt": "Invalid password salt",
    "auth/invalid-phone-number": "Invalid phone number",
    "auth/invalid-photo-url": "Invalid photo URL",
    "auth/invalid-provider-data": "Invalid provider data",
    "auth/invalid-provider-id": "Invalid provider ID",
    "auth/invalid-oauth-responsetype": "Invalid OAuth response type",
    "auth/invalid-session-cookie-duration": "Invalid session cookie duration",
    "auth/invalid-uid": "Invalid UID",
    "auth/invalid-user-import": "Invalid user import",
    "auth/maximum-user-count-exceeded": "Maximum user count exceeded",
    "auth/missing-android-pkg-name": "Missing Android package name",
    "auth/missing-continue-uri": "Missing continue URL",
    "auth/missing-hash-algorithm": "Missing hash algorithm",
    "auth/missing-ios-bundle-id": "Missing iOS bundle ID",
    "auth/missing-uid": "Missing UID",
    "auth/missing-oauth-client-secret": "Missing OAuth client secret",
    "auth/operation-not-allowed": "Operation not allowed",
    "auth/phone-number-already-exists": "Phone number already exists",
    "auth/project-not-found": "Project not found",
    "auth/reserved-claims": "Reserved claims provided",
    "auth/session-cookie-expired": "Session cookie expired",
    "auth/session-cookie-revoked": "Session cookie revoked",
    "auth/too-many-requests": "Too many requests, please try again later",
    "auth/uid-already-exists": "UID already exists",
    "auth/unauthorized-continue-uri": "Unauthorized continue URL",
    "auth/user-not-found": "User not found",
    "auth/network-request-failed":
        "We are unable to connect to firebase. Please check your network and try again",
};

export function getFirebaseErrorMessage(errorCode: string): string {
    return firebaseErrorMessages[errorCode] || "An unknown error occurred";
}
